name: Daily Food Tracker CI

on:
  pull_request:
  push:
    branches: [main]

env:
  DATABASE_URL: "file:./packages/core/prisma/dev.db"
  DATABASE_PROVIDER: "sqlite"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Generate Prisma client
        run: |
          cd packages/core
          pnpm prisma generate
          
      - name: Run database migrations
        run: |
          cd packages/core
          pnpm prisma migrate deploy
          
      - name: Lint code
        run: pnpm lint
        
      - name: Run unit tests
        run: pnpm test
        
      - name: Build all packages
        run: pnpm build
        
      - name: Smoke test dev server
        run: pnpm smoke
  
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Install Playwright browsers
        run: |
          cd apps/web
          pnpm exec playwright install --with-deps
          
      - name: Set up database for E2E tests
        run: |
          cd packages/core
          pnpm prisma generate
          pnpm prisma migrate deploy
          pnpm prisma db seed
          
      - name: Build web app
        run: |
          cd apps/web
          pnpm build
          
      - name: Start web app
        run: |
          cd apps/web
          pnpm start &
          sleep 5
          
      - name: Run Playwright tests
        run: |
          cd apps/web
          pnpm test:e2e
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
